name: Build and deploy ASP.Net Core app to Azure Web App - b2s-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    timeout-minutes: 20  # Set a timeout of 20 minutes for the deployment job

    steps:
      - name: Stream Azure Deployment Logs with Debug
        run: az webapp log tail --name b2s-api --resource-group b2s --debug
        
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Clear Deployment Cache
        run: |
          echo "Clearing deployment cache..."
          rm -rf site/deployments

      - name: Deploy to Azure Web App with Debug Logging
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'b2s-api'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_666CAA1D38694C0493F07C5AE3574B33 }}
        env:
          ACTIONS_STEP_DEBUG: true  # Enable verbose logging for debugging
